# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-15 13:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20170215_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='userLogo',
            field=models.FileField(blank=True, upload_to='user_images'),
        ),
    ]
